### ISSUE TITLE
npm installation errors

### ISSUE THREAD

**Issue by Varbaek** [ekmartin/slack-irc#182]
```
/usr/local/bin/slack-irc -> /usr/local/lib/node_modules/slack-irc/dist/index.js

> iconv@2.1.11 install /usr/local/lib/node_modules/slack-irc/node_modules/iconv
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.6-x86_64-linode78
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slack-irc/node_modules/iconv
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN install:iconv@2.1.11 iconv@2.1.11 install: `node-gyp rebuild`
npm WARN install:iconv@2.1.11 Exit status 1

> node-icu-charset-detector@0.1.4 install /usr/local/lib/node_modules/slack-irc/node_modules/node-icu-charset-detector
> node-gyp rebuild

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:304:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.8.6-x86_64-linode78
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/slack-irc/node_modules/node-icu-charset-detector
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN install:node-icu-charset-detector@0.1.4 node-icu-charset-detector@0.1.4 install: `node-gyp rebuild`
npm WARN install:node-icu-charset-detector@0.1.4 Exit status 1
/usr/local/lib
└─┬ slack-irc@3.9.0
  ├─┬ @slack/client@3.6.0
  │ ├── async@1.5.2
  │ ├── bluebird@3.4.6
  │ ├── eventemitter3@1.2.0
  │ ├─┬ https-proxy-agent@1.0.0
  │ │ ├─┬ agent-base@2.0.1
  │ │ │ └── semver@5.0.3
  │ │ ├─┬ debug@2.3.3
  │ │ │ └── ms@0.7.2
  │ │ └── extend@3.0.0
  │ ├── inherits@2.0.3
  │ ├─┬ request@2.79.0
  │ │ ├── aws-sign2@0.6.0
  │ │ ├── aws4@1.5.0
  │ │ ├── caseless@0.11.0
  │ │ ├─┬ combined-stream@1.0.5
  │ │ │ └── delayed-stream@1.0.0
  │ │ ├── forever-agent@0.6.1
  │ │ ├─┬ form-data@2.1.2
  │ │ │ └── asynckit@0.4.0
  │ │ ├─┬ har-validator@2.0.6
  │ │ │ ├─┬ chalk@1.1.3
  │ │ │ │ ├── ansi-styles@2.2.1
  │ │ │ │ ├── escape-string-regexp@1.0.5
  │ │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ │ └── ansi-regex@2.0.0
  │ │ │ │ ├── strip-ansi@3.0.1
  │ │ │ │ └── supports-color@2.0.0
  │ │ │ ├─┬ is-my-json-valid@2.15.0
  │ │ │ │ ├── generate-function@2.0.0
  │ │ │ │ ├─┬ generate-object-property@1.2.0
  │ │ │ │ │ └── is-property@1.0.2
  │ │ │ │ ├── jsonpointer@4.0.0
  │ │ │ │ └── xtend@4.0.1
  │ │ │ └─┬ pinkie-promise@2.0.1
  │ │ │   └── pinkie@2.0.4
  │ │ ├─┬ hawk@3.1.3
  │ │ │ ├── boom@2.10.1
  │ │ │ ├── cryptiles@2.0.5
  │ │ │ ├── hoek@2.16.3
  │ │ │ └── sntp@1.0.9
  │ │ ├─┬ http-signature@1.1.1
  │ │ │ ├── assert-plus@0.2.0
  │ │ │ ├─┬ jsprim@1.3.1
  │ │ │ │ ├── extsprintf@1.0.2
  │ │ │ │ ├── json-schema@0.2.3
  │ │ │ │ └── verror@1.3.6
  │ │ │ └─┬ sshpk@1.10.1
  │ │ │   ├── asn1@0.2.3
  │ │ │   ├── assert-plus@1.0.0
  │ │ │   ├── bcrypt-pbkdf@1.0.0
  │ │ │   ├─┬ dashdash@1.14.1
  │ │ │   │ └── assert-plus@1.0.0
  │ │ │   ├── ecc-jsbn@0.1.1
  │ │ │   ├─┬ getpass@0.1.6
  │ │ │   │ └── assert-plus@1.0.0
  │ │ │   ├── jodid25519@1.0.2
  │ │ │   ├── jsbn@0.1.0
  │ │ │   └── tweetnacl@0.14.4
  │ │ ├── is-typedarray@1.0.0
  │ │ ├── json-stringify-safe@5.0.1
  │ │ ├─┬ mime-types@2.1.13
  │ │ │ └── mime-db@1.25.0
  │ │ ├── oauth-sign@0.8.2
  │ │ ├── qs@6.3.0
  │ │ ├── stringstream@0.0.5
  │ │ ├─┬ tough-cookie@2.3.2
  │ │ │ └── punycode@1.4.1
  │ │ ├── tunnel-agent@0.4.3
  │ │ └── uuid@3.0.1
  │ ├── retry@0.9.0
  │ ├── url-join@0.0.1
  │ └─┬ ws@1.1.1
  │   ├── options@0.0.6
  │   └── ultron@1.0.2
  ├── check-env@1.2.0
  ├─┬ commander@2.9.0
  │ └── graceful-readlink@1.0.1
  ├─┬ irc@0.5.0
  │ └── irc-colors@1.3.1
  ├── lodash@4.17.2
  ├── strip-json-comments@2.0.1
  └─┬ winston@2.2.0
    ├── async@1.0.0
    ├── colors@1.0.3
    ├── cycle@1.0.3
    ├── eyes@0.1.8
    ├── isstream@0.1.2
    ├── pkginfo@0.3.1
    └── stack-trace@0.0.9

```

**Comment by ekmartin** [comment]
Are you sure the install doesn't complete (i.e. did you try running `slack-irc` afterwards)?
The errors you're seeing at the top is from node-icu-charset-detector, which is an optional dependency of node-irc (so the install should complete even if that fails).

**Comment by Varbaek** [comment]
It did install on Ubuntu 16.10 but I just wanted to raise that the installer returns this error.

On Debian 8 it didn't work though, but that's a separate issue.
