### ISSUE TITLE
IT DOESNT WORK

### ISSUE THREAD

**Issue by paigeadelethompson** [ekmartin/slack-irc#263]
```
> slack-irc@3.11.3 start /app
> node dist/index.js "--config" "/config/config.json"

[winston] Attempt to write logs with no transports {"message":"Connecting to IRC and Slack","level":"debug"}
error: Response not OK:  invalid_auth
error: Disconnecting because invalid_auth is not recoverable
error:  message=invalid_auth, stack=Error: invalid_auth
    at handleHttpResponse (/app/node_modules/@slack/client/lib/clients/transports/call-transport.js:103:17)
    at handleTransportResponse (/app/node_modules/@slack/client/lib/clients/transports/call-transport.js:153:19)
    at apply (/app/node_modules/lodash/lodash.js:478:17)
    at wrapper (/app/node_modules/lodash/lodash.js:5323:16)
    at Request.handleRequestTranportRes (/app/node_modules/@slack/client/lib/clients/transports/request.js:20:5)
    at apply (/app/node_modules/lodash/lodash.js:478:17)
    at Request.wrapper [as _callback] (/app/node_modules/lodash/lodash.js:5323:16)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (events.js:193:13)
    at Request.<anonymous> (/app/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:193:13)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:281:20)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

```

**Comment by paigeadelethompson** [comment]
WHY CANT YA JUST PUT THE RIGHT INFO https://api.slack.com/custom-integrations/legacy-tokens

**Comment by paigeadelethompson** [comment]
Ok so I did get this all to work the way
