### ISSUE TITLE
`process.env.CONFIG_FILE.endsWith('.js')` -- "undefined is not a function"

### ISSUE THREAD

**Issue by nevik** [ekmartin/slack-irc#70]
When trying to run `slack-irc`, I get the following error:

```
$ ~/node_modules/.bin/slack-irc
~/node_modules/slack-irc/dist/cli.js:60
  var config = process.env.CONFIG_FILE.endsWith('.js') ? require(completePath)
                                       ^
TypeError: undefined is not a function
    at run (~/node_modules/slack-irc/dist/cli.js:60:40)
    at Object.<anonymous> (~/node_modules/slack-irc/dist/index.js:27:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

This happens both when use the `CONFIG_FILE` env variable, and when use the `--config` CLI switch.

This is on a Ubuntu 12.04 server, with the following versions:

```
$ nodejs -v
v0.12.9
$ npm -v
3.5.3
```

I have literally zero idea of NodeJS (and npm) -- what can I do to make slack-irc work?

**Comment by ekmartin** [comment]
This has been fixed in version 3.7.1, sorry! Forgot that node 0.12 didn't have support for `String.prototype.endsWith`, so added babel-polyfill now.

**Comment by nevik** [comment]
Awesome, thanks for your quick response! I'll test this soon and report back if there are any more problems :)

**Comment by ekmartin** [comment]
Great!
