### ISSUE TITLE
cant build project

### ISSUE THREAD

**Issue by danhimalplanet** [ekmartin/slack-irc#76]
trying!

$ nvm use stable
Now using node v5.5.0 (npm v3.3.12)
$ npm --version
3.3.12
$ babel lib --out-dir dist
Error: Couldn't find preset "stage-0" relative to directory "/home/cccp/experiment/slack-irc"
    at OptionManager.mergePresets (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:327:17)
    at OptionManager.mergeOptions (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:287:12)
    at OptionManager.addConfig (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:221:10)
    at OptionManager.findConfigs (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:16)
    at OptionManager.init (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:412:12)
    at File.initOptions (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transform (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/lib/babel/util.js:53:22)
    at Object.compile (/home/cccp/.nvm/versions/node/v5.5.0/lib/node_modules/babel-cli/lib/babel/util.js:62:12)

**Comment by ekmartin** [comment]
Hi! What's the output of `npm install` followed by `npm run build`?

**Comment by danhimalplanet** [comment]
I'm dumb.

Forgot to do npm install.

all works.

carry on.

**Comment by ekmartin** [comment]
No problem, glad you got it working!
